services:
  - type: web
    name: block-buster-app
    env: ruby
    region: oregon
    plan: free
    buildCommand: "bundle install && yarn install && bundle exec rake assets:precompile db:migrate"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: block-buster-app-db
          property: connectionString

databases:
  - name: block-buster-app-db
    engine: postgresql
    version: 14
    starterPlan: true
