default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: block_buster
  username: postgres
  password: 02125019
  host: localhost
  port: 5432

test:
  <<: *default
  database: block_buster_app_test
  username: postgres
  password: 02125019
  host: localhost
  port: 5432

# Configuración para producción en Render
production:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: 5432
  sslmode: require
